export const APPOINTMENTINFO = [
  { label: "Appointment Id", key: "id" },
  { label: "Name", key: "patientname" },
  { label: "Age", key: "age" },
  { label: "Gender", key: "gender" },
  { label: "Blood Group", key: "bloodgroup" },
  { label: "Is Corona Vaccinated", key: "vaccinated" },
  { label: "Reason", key: "reason" },
  { label: "Doctor Name", key: "doctorname" },
  { label: "Specialist", key: "specialist" },
  { label: "Appointment Date", key: "appointmentdate" },
  { label: "Scheduled Time", key: "scheduledTime" },
  { label: "Appointment Status", key: "status" },
  { label: "Appointment Declined Reason", key: "declinedreason" },
  { label: "Body Temperature", key: "checkupstatus.bodytemperature" },
  { label: "Systolic Pressure", key: "checkupstatus.systolicpressure" },
  { label: "Diastolic Pressure", key: "checkupstatus.diastolicpressure" },
  { label: "Sugar Level", key: "checkupstatus.sugarlevel" },
  { label: "Doctor Advice", key: "checkupstatus.doctoradvice" },
  { label: "Medical Prescription", key: "checkupstatus.medicalprescription" },
  { label: "Scan Reports", key: "imgUrl" },
];
